version: "3.9"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=elecciones
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SECRET_KEY=e_(x5@3t65y996!ch$m*uf6y3j1a8zeh$h4=uiktp0c9oarkla
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  database-data: 
