service: elecciones2021
provider:
  name: aws
  runtime: python3.8
  stage: dev
  profile: ${opt:stage, 'dev'}
  stackName: elecciones2021-stack-${opt:stage, self:provider.stage, 'dev'} 
  apiName: elecciones2021-apigtw-${opt:stage, self:provider.stage, 'dev'}

  lambdaHashingVersion: 20201221 # optional, version of hashing algorithm that should be used by the framework

plugins:
  - serverless-wsgi
  - serverless-python-requirements
functions:
  app:
    handler: wsgi_handler.handler
    environment: ${self:custom.variables}
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
custom:
  wsgi:
    app: backend.wsgi.application
    packRequirements: false
  variables: ${file(./env-${opt:stage, self:provider.stage, 'dev'}.yml)}