# Generated by Django 3.1.4 on 2021-01-05 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('ubigeo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=150)),
                ('distrito_electoral', models.CharField(max_length=150)),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ubigeo',
            },
        ),
    ]
