# Generated by Django 3.1.4 on 2021-01-25 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jne_idhojavida', models.IntegerField()),
                ('jne_idhvingresos', models.IntegerField()),
                ('renta_bruta_privado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('renta_bruta_publico', models.DecimalField(decimal_places=2, max_digits=15)),
                ('renta_individual_privado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('renta_individual_publico', models.DecimalField(decimal_places=2, max_digits=15)),
                ('otros_ingresos_privado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('otros_ingresos_publico', models.DecimalField(decimal_places=2, max_digits=15)),
                ('anio_ingresos', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Candidato Ingresos',
                'verbose_name_plural': 'Candidato Ingresos',
                'db_table': 'candidato_ingreso',
            },
        ),
        migrations.CreateModel(
            name='CandidatoInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jne_idhojavida', models.IntegerField()),
                ('jne_idhvbieninmueble', models.IntegerField()),
                ('jne_strinmueblesunarp', models.IntegerField()),
                ('jne_decautovaluo', models.FloatField()),
                ('direccion', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order', models.IntegerField()),
                ('comentario', models.TextField(null=True)),
                ('partida_sunarp', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(max_length=80)),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Candidato Bienes Inmuebles',
                'verbose_name_plural': 'Candidato Bienes Inmuebles',
                'db_table': 'candidato_inmueble',
            },
        ),
        migrations.CreateModel(
            name='CandidatoMueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jne_idhojavida', models.IntegerField()),
                ('jne_idhvbienmueble', models.IntegerField()),
                ('caracteristica', models.CharField(max_length=100)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField()),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('placa', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehiculo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Candidato Bienes Muebles',
                'verbose_name_plural': 'Candidato Bienes Muebles',
                'db_table': 'candidato_mueble',
            },
        ),
    ]
