# Generated by Django 3.1.4 on 2021-01-07 06:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jne_idcandidato', models.IntegerField()),
                ('jne_idhojavida', models.IntegerField()),
                ('jne_estado_lista', models.CharField(max_length=150)),
                ('jne_estado_expediente', models.CharField(max_length=150)),
                ('jne_estado_hojavida', models.CharField(max_length=150)),
                ('jne_posicion', models.IntegerField()),
                ('jne_organizacion_politica', models.CharField(max_length=150)),
                ('cargo_id', models.IntegerField()),
                ('proceso_id', models.IntegerField()),
                ('organizacion_politica_id', models.IntegerField()),
                ('documento_identidad', models.CharField(max_length=150)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(max_length=150)),
                ('nombres', models.CharField(max_length=150)),
                ('profesion', models.CharField(max_length=150)),
                ('nivel_estudio_id_max', models.IntegerField()),
                ('region', models.CharField(max_length=150)),
                ('distrito_electoral', models.CharField(max_length=150)),
                ('ubigeo_postula', models.CharField(max_length=150)),
                ('ruta_archivo', models.CharField(max_length=150)),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'candidato',
            },
        ),
        migrations.AlterField(
            model_name='indicadorcategoriaorganizacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadorescategoriaorg', to='api.organizacionpolitica'),
        ),
        migrations.CreateModel(
            name='IndicadorCategoriaCandidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('porcentaje', models.FloatField()),
                ('alerta', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_categoria_candidato', to='api.candidato')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicador')),
                ('indicador_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicadorcategoria')),
            ],
            options={
                'db_table': 'indicador_categoria_candidato',
            },
        ),
    ]
