# Generated by Django 3.1.4 on 2021-01-03 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('alerta', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': '_indicador',
            },
        ),
        migrations.CreateModel(
            name='IndicadorCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('alerta', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': '_indicador_categoria',
            },
        ),
        migrations.CreateModel(
            name='IndicadorCategoriaOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador_id', models.IntegerField()),
                ('indicador_categoria_id', models.IntegerField()),
                ('organizacion_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('porcentaje', models.FloatField()),
                ('alerta', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': '_indicador_categoria_organizacion',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionPolitica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fundacion_anio', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('jne_idorganizacionpolitica', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'organizacion_politica',
            },
        ),
        migrations.DeleteModel(
            name='PartidoPolitico',
        ),
    ]
