# Generated by Django 3.1.4 on 2021-02-08 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidatoingreso_candidatoinmueble_candidatomueble'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoMedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jne_idhojavida', models.IntegerField()),
                ('titulo', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=250)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('web', 'Web')], default='web', max_length=10)),
                ('fecha', models.DateField()),
                ('medio', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Candidato Medios',
                'verbose_name_plural': 'Candidato Medios',
                'db_table': 'candidato_medio',
            },
        ),
        migrations.AlterField(
            model_name='candidatomueble',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
