# Generated by Django 3.1.4 on 2021-01-04 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210103_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadorcategoria',
            name='indicador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicador'),
        ),
        migrations.AlterField(
            model_name='indicadorcategoriaorganizacion',
            name='indicador_categoria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicadorcategoria'),
        ),
        migrations.AlterField(
            model_name='indicadorcategoriaorganizacion',
            name='indicador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicador'),
        ),
        migrations.AlterField(
            model_name='indicadorcategoriaorganizacion',
            name='organizacion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizacionpolitica'),
        ),
    ]
