# Generated by Django 3.1.4 on 2021-02-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organizacionplan_organizacionplancriterio_organizacionplandetalle_plancriterio'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatomedio',
            name='imagen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
