# Generated by Django 3.1.4 on 2021-02-20 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_candidatomedio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoProductividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jne_idhojavida', models.IntegerField()),
                ('periodo_inicio', models.IntegerField()),
                ('periodo_fin', models.IntegerField()),
                ('nro_leyes_publicado', models.IntegerField()),
                ('nro_leyes_total', models.IntegerField()),
                ('porcentaje_leyes', models.FloatField()),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Candidato productividad',
                'verbose_name_plural': 'Candidato productividad',
                'db_table': 'candidato_productividad',
            },
        ),
        migrations.CreateModel(
            name='CandidatoProyectoLey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jne_idhojavida', models.IntegerField()),
                ('ley_id', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Candidatos proyectos de ley',
                'verbose_name_plural': 'Candidatos proyectos de ley',
                'db_table': 'candidato_proyecto_ley',
            },
        ),
        migrations.CreateModel(
            name='ProyectoLey',
            fields=[
                ('ley_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=150)),
                ('legislatura', models.CharField(max_length=150)),
                ('fecha_presentacion', models.DateField(null=True)),
                ('numero', models.CharField(max_length=150)),
                ('proponente', models.CharField(max_length=150)),
                ('grupo_parlamentario', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=255)),
                ('sumilla', models.CharField(max_length=255, null=True)),
                ('autores', models.CharField(max_length=255, null=True)),
                ('adherentes', models.CharField(max_length=150, null=True)),
                ('seguimiento', models.CharField(max_length=150, null=True)),
                ('iniciativa_agrupadas', models.CharField(max_length=150, null=True)),
                ('numero_simple', models.CharField(max_length=150, null=True)),
                ('fecha_ultima', models.DateField(null=True)),
                ('estado', models.CharField(max_length=150)),
                ('link_detalle', models.CharField(max_length=255, null=True)),
                ('periodo_inicio', models.CharField(max_length=150)),
                ('periodo_fin', models.CharField(max_length=150)),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Proyecto de ley',
                'verbose_name_plural': 'Proyecto de ley',
                'db_table': 'proyecto_ley',
            },
        ),
    ]
