# Generated by Django 3.1.4 on 2021-04-04 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_candidatoinfoadicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoAnotacionMarginal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jne_idhojavida', models.IntegerField()),
                ('jne_idanotacionmarginal', models.IntegerField()),
                ('jne_idtipoanotacion', models.IntegerField()),
                ('jne_strtipoanotacion', models.CharField(max_length=150)),
                ('dice', models.CharField(max_length=4000)),
                ('debedecir', models.CharField(max_length=4000)),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Candidato anotacion marginal',
                'verbose_name_plural': 'Candidato anotacion marginal',
                'db_table': 'candidato_anotacion_marginal',
            },
        ),
    ]
