# Generated by Django 3.1.4 on 2021-04-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_candidatoanotacionmarginal'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='electo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizacionpolitica',
            name='electo',
            field=models.BooleanField(default=False),
        ),
    ]
