# Generated by Django 3.1.4 on 2021-04-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210419_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='votos_validos',
            field=models.BigIntegerField(default=0),
        ),
    ]
